project:
  type: website

website:
  title: "Donovan Lab"
  navbar:
    tools:
      - icon: github
        href: https://github.com/Donovan-Lab-at-HIMB
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Publications
      - href: people.qmd
        text: People
      - href: join.qmd
        text: Join
      - href: codeconduct.qmd
        text: "Code of Conduct"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto